version: "3"
services:
  safespace-frontend:
    tty: true
    container_name: safespace-frontend
    build:
      context: ./safespace-frontend
    ports:
      - "3000:3000"
    volumes:
      -  /usr/src/app/node_modules
      - ./safespace-frontend:/usr/src/app